Update npm-pipeline.yml

diff --git a/.github/workflows/npm-pipeline.yml b/.github/workflows/npm-pipeline.yml
--- a/.github/workflows/npm-pipeline.yml
+++ b/.github/workflows/npm-pipeline.yml
@@ -40,6 +40,13 @@ jobs:
       - name: ⬇️ Checkout del Código
         uses: actions/checkout@v4
 
+      - name: 🕵️ Debug de Secretos
+        run: |
+          if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then echo "❌ Error: AWS_ACCESS_KEY_ID está vacío"; exit 1; fi
+          if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then echo "❌ Error: AWS_SECRET_ACCESS_KEY está vacío"; exit 1; fi
+          if [ -z "${{ vars.AWS_REGION }}" ]; then echo "❌ Error: AWS_REGION está vacío"; exit 1; fi
+          echo "✅ GitHub encontró todas las variables y secretos."
+
       - name: 🔑 Configurar credenciales de AWS
         uses: aws-actions/configure-aws-credentials@v4
         with:
